name: Test Airship

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: Airship

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Download latest Airship
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: FlatLang/Airship
          file: airship.js

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build Airship
        run: |
          node ./airship.js install https://github.com/FlatLang/Flat.git

      - name: Build Airship
        working-directory: Airship
        run: |
          node ../airship.js install
          node dist/airship.js install --link

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: airship.js
          path: Airship/dist/airship.js

      - name: Build Airship Tests with Airship
        working-directory: Airship
        run: |
          node dist/airship.js install test

      - name: Run Airship Tests
        working-directory: Airship
        run: |
          node dist/airship.js run test

      - name: Checkout Stability-Test
        uses: actions/checkout@master
        with:
          repository: FlatLang/Stability-Test
          path: Stability-Test

      - name: Build Stability-Test with Airship
        working-directory: Stability-Test
        run: |
          node ../Airship/dist/airship.js install --link
          node ../Airship/dist/airship.js install test

      - name: Run Stability-Test
        working-directory: Stability-Test
        run: |
          node dist/test.js
