name: Create Master Airship Release

on:
  push:
    branches: [master]

jobs:
  create-master-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_MANAGEMENT_TOKEN }}

      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 2
          delete_tag_pattern: master-
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_MANAGEMENT_TOKEN }}

      - name: Create and push tag
        run: |
          git tag master-$(git rev-parse --short HEAD)
          git push origin master-$(git rev-parse --short HEAD)
