name: Create Airship Prerelease

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.5.0
        with:
          java-version: 8
          maven-version: 3.8.6

      - uses: actions/checkout@v3
        with:
          path: Airship

      - name: Download latest Airship
        uses: FlatLang/fetch-airship@master
        with:
          includePrerelease: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build Airship es6
        working-directory: Airship
        run: |
          node ../airship.js install -t es6

      - name: Replace Airship artifact
        run: |
          rm airship.js
          mv Airship/dist/airship.js airship.js

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "airship.js"
          token: ${{ secrets.CREATE_RELEASE_TOKEN }}
          tag: "${{github.ref_name}}"
          prerelease: true
          body: ""
          generateReleaseNotes: true
