name: Create Airship Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.8.0
        with:
          java-version: 8

      - uses: actions/checkout@v3
        with:
          path: Airship

      - name: Download latest Airship
        uses: FlatLang/fetch-airship@master
        with:
          includePrerelease: true

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build Airship es6
        working-directory: Airship
        run: |
          node ../airship.js install -t es6

      - name: Replace Airship artifact
        run: |
          rm airship.js
          mv Airship/dist/airship.js airship.js

      - name: Get latest release of Airship
        uses: rez0n/actions-github-release@main
        id: stable_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: "${{ github.repository }}"
          type: "stable"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "airship.js"
          token: ${{ secrets.WORKFLOW_MANAGEMENT_TOKEN }}
          tag: "${{github.ref_name}}"
          prerelease: false
          body: "**Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.stable_release.outputs.release }}...${{github.ref_name}}"
          generateReleaseNotes: false
